name: Build IPA (Checkpointed)

on:
  workflow_dispatch:
  push:
    branches:
      - build-action

jobs:
  setup:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Cache CocoaPods Specs
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-specs-${{ hashFiles('Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-specs-

      - name: Install CocoaPods
        id: install_pods
        run: |
          sudo gem install cocoapods
          if [ ! -d "Pods" ]; then
            echo "No Pods directory found, installing..."
            pod install
            echo "fresh_install=true" >> $GITHUB_OUTPUT
          else
            echo "Pods directory exists, skipping install."
            echo "fresh_install=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Pods Artifact (only if freshly installed)
        if: steps.install_pods.outputs.fresh_install == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pods
          path: Pods

  build:
    runs-on: macos-13
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Download Pods
        uses: actions/download-artifact@v4
        with:
          name: pods
          path: Pods

      - name: Ensure Pods scripts are executable
        run: |
          find Pods/Target\ Support\ Files -name "*.sh" -exec chmod +x {} \;
        
      - name: Build with Xcode
        run: |
          xcodebuild -workspace VLC.xcworkspace \
                       -scheme VLC-iOS \
                       -configuration Release \
                       -sdk iphoneos \
                       -archivePath $PWD/build/VLC.xcarchive \
                       CODE_SIGN_IDENTITY="" \
                       CODE_SIGNING_REQUIRED=NO \
                       CODE_SIGNING_ALLOWED=NO \
                       archive

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: vlc-archive
          path: build/VLC.xcarchive

  export:
    runs-on: macos-13
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download Archive
        uses: actions/download-artifact@v4
        with:
          name: vlc-archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/VLC.xcarchive \
                     -exportOptionsPlist $PWD/ExportOptions.plist \
                     -exportPath $PWD/ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: vlc-ios-ipa
          path: ipa/*.ipa
