# Workflow to periodically sync code from VideoLAN GitLab upstream repository
name: Sync from GitLab Upstream

on:
  schedule:
    - cron: '30 2 * * *'  # Daily at 02:30 UTC
  workflow_dispatch:      # Allows manual trigger
  push:
    branches:
      - actions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add GitLab upstream
        run: |
          git remote add upstream https://code.videolan.org/videolan/vlc-ios.git
          git fetch upstream

      - name: Rebase onto upstream/master
        run: |
          git checkout master
          git rebase upstream/master

      - name: Push changes to GitHub
        run: |
          echo "Using remote: https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:master
